/*
-- -----------------------------------------------------------------------------------
-- V. magnitude analysis - comparing the measure values across different categories
--                         ∑ [measure] by [dimension]
-- -----------------------------------------------------------------------------------

Purpose: Compare business performance across different dimensions 
such as country, gender, product category, and customer revenue contribution.
*/


-- 1. find total customers by country
SELECT
country,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- 2. find total customers by gender
SELECT
gender,
COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- 3. find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- 4. what is the average cost in each category?
SELECT
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- 5. what is the total revenue generated for each category?
SELECT
coalesce(p.category,'n/a') AS category,
coalesce(SUM(f.price),0) AS total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales f
ON p.product_key = f.product_key
GROUP BY coalesce(p.category,'n/a')
ORDER BY total_revenue DESC;


SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- 6. find total revenue generated by each customer?
SELECT   
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;


-- 7. what is the distribution of sold items across countries?
SELECT   
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

/*
LOW CARDINALITY DIMENSION - Dimension with few unique values. (e.g. category,gender,marital status,...)
HIGH CARDINALITY DIMENSION - Dimension with large number of unique values. (e.g. product,customer,address,..)
*/

